[pytest]
addopts=
    -v
    --headed

    # -----------
    # Debug options
    # -----------
    --video=off
    --tracing=retain-on-failure
    --screenshot=only-on-failure

    # --------Report---------
    --html=reports/myreport.html --self-contained-html --capture=tee-sys
    --alluredir=reports/allure-results

    # --------parallel execution-----
    -n=2

    #--------flaky test----------
    --reruns 1
    --reruns-delay 3

    #-------grouping test--------
    #-m "sanity"
    #-m "regression"
    #-m "smoke"

#markers=
    #sanity
    #regression
    #smoke




